[package]
name = "mathsys"
version = "7.0.0"
edition = "2024"
authors = ["Alejandro Vaz <alejandro.vaz.myt@gmail.com>"]
description = "The Natural Language of Math."
license = "MIT"
repository = "https://github.com/alejandro-vaz/mathsys"

[[bin]]
name = "mathsys"
path = "main.rs"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true
debug = false

[dependencies]
colored = "3.1.1"
regex = "1.12.3"
indexmap = "2.13.0"
ahash = "0.8.12"
smallvec = "1.15.1"
rustc_version_runtime = "0.3.0"
strum_macros = "0.27.2"